fix

diff --git a/check-actions/action.yml b/check-actions/action.yml
--- a/check-actions/action.yml
+++ b/check-actions/action.yml
@@ -10,32 +10,56 @@ runs:
         sudo apt update
         sudo apt install -y yq shellcheck
 
+    - name: Check scripts
+      shell: bash
+      run: |
+        SCRIPT_FILES="$(find . -type f -name '*.sh')"
+        ERRORS=0
+
+        for script in $SCRIPT_FILES; do
+          echo "::group::Checking script file: $script"
+
+          # SC2148: script missing shebang
+          # SC2296: github variables expansion: ${ {something} }
+          shellcheck "$script" -e SC2148 -e SC2296
+
+          echo "::endgroup::"
+        done
+
+        if [ "$ERRORS" -gt 0 ]; then
+          echo "There are $ERRORS issues."
+          exit 1
+        fi
+
     - name: Check actions
       shell: bash
       run: |
         ACTION_FILES="$(find . -type f -name action.yml)"
-        CHECK_FAILED=false
+        ERRORS=0
 
         for action in $ACTION_FILES; do
+          if [ "$(yq -c '.runs | has("steps")' "$action")" != "true" ]; then
+            continue
+          fi
+
           echo "::group::Checking action file: $action"
 
-          yq -c '.runs.steps[]? | select(has("run"))' "$action" |
           while IFS= read -r step; do
 
             NAME=$(echo "$step" | yq -r '.name // "Unnamed"')
             echo "Checking step: $NAME"
 
             # SC2148: script missing shebang
-            # SC2296: github variables expansion: ${\{something}}
-            printf '%s\n' "$step" | yq -r '.run' | shellcheck - -e SC2148 -e SC2296 || export CHECK_FAILED=true
+            # SC2296: github variables expansion: ${ {something} }
+            printf '%s\n' "$step" | yq -r '.run' | shellcheck - -e SC2148 -e SC2296 || ((ERRORS++))
 
-          done
+          done < <(yq -o=json -I=0 '.runs.steps[]? | select(has("run"))' "$action")
 
           echo "::endgroup::"
         done
 
-        if [ "$CHECK_FAILED" = true ]; then
-          echo "One or more shell scripts have issues."
+        if [ "$ERRORS" -gt 0 ]; then
+          echo "There are $ERRORS issues."
           exit 1
         fi
 
@@ -43,27 +67,30 @@ runs:
       shell: bash
       run: |
         WORKFLOW_FILES="$(find .github/workflows -type f -name '*.yml')"
-        CHECK_FAILED=false
+        ERRORS=0
 
         for workflow in $WORKFLOW_FILES; do
+          if [ "$(yq -c '.jobs | has("steps")' "$workflow")" != "true" ]; then
+            continue
+          fi
+
           echo "::group::Checking workflow file: $workflow"
 
-          yq -c '.jobs[]?.steps[]? | select(has("run"))' "$workflow" |
           while IFS= read -r step; do
 
             NAME=$(echo "$step" | yq -r '.name // "Unnamed"')
             echo "Checking step: $NAME"
 
             # SC2148: script missing shebang
-            # SC2296: github variables expansion: ${\{something}}
-            printf '%s\n' "$step" | yq -r '.run' | shellcheck - -e SC2148 -e SC2296 || export CHECK_FAILED=true
+            # SC2296: github variables expansion: ${ {something} }
+            printf '%s\n' "$step" | yq -r '.run' | shellcheck - -e SC2148 -e SC2296 || ((ERRORS++))
 
-          done
+          done < <(yq -o=json -I=0 '.jobs[]?.steps[]? | select(has("run"))' "$workflow")
 
           echo "::endgroup::"
         done
 
-        if [ "$CHECK_FAILED" = true ]; then
-          echo "One or more shell scripts have issues."
+        if [ "$ERRORS" -gt 0 ]; then
+          echo "There are $ERRORS issues."
           exit 1
         fi
